attrs:
  # https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
  # https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
  # Dataset Description
  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: ADCP
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v79

  title: Up-looking ADCP
  description: >-
    Add summary here
  keywords: Sequim, data, marine, channel, water velocity, water direction, flows
  # Attribution
  creator_country: USA
  #creator_email:
  creator_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  creator_institution_url: https://www.pnnl.gov/
  creator_sector: other
  creator_type: institution
  creator_url: https://www.pnnl.gov/
  institution: Pacific Northwest National Laboratory (PNNL)
  publisher_country: USA
  #publisher_email:
  publisher_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  publisher_url: https://www.pnnl.gov/

  # Platform and Instrument
  platform: lander
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  instrument: In Situ/Laboratory Instruments > Current/Wind Meters > Current Meters
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Nortek Signature2000

  # Geospatial and Time
  geospatial_bounds: Point ((48.0804 -123.0449))
  geospatial_bounds_crs: "EPSG:4326"
  time_coverage_start: "2022-05-18T21:28:46"
  time_coverage_duration: "01:00:00"
  time_coverage_resolution: "00:00:00.500"

  # TSDAT specific parameters
  location_id: asv
  dataset_name: sig1000
  data_level: b1

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: Time
      standard_name: time
      timezone: UTC
      description: "Timestamp for data generated by ADCP beams 1-4"
      coverage_content_type: coordinate
  time_b5:
    dims: [time_b5]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: Time
      standard_name: time
      timezone: UTC
      description: "Timestamp for data generated by ADCP beam 5"
      coverage_content_type: coordinate
  range:
    dims: [range]
    dtype: float32
    attrs:
      description: "Distance to the center of each depth bin"
      long_name: Profile Range
      units: m
      coverage_content_type: coordinate
  range_b5:
    dims: [range_b5]
    dtype: float32
    attrs:
      description: "Distance to the center of each depth bin"
      long_name: Profile Range
      units: m
      coverage_content_type: coordinate
  dir:
    dims: [dir]
    dtype: str
    attrs:
      long_name: Reference Frame
      units: "1"
      coverage_content_type: coordinate
  beam:
    dims: [beam]
    data: [1, 2, 3, 4]
    dtype: int
    attrs:
      long_name: Beam Reference Frame
      units: "1"
      coverage_content_type: coordinate
  inst:
    dims: [inst]
    dtype: str
    attrs:
      long_name: Instrument Reference Frame
      units: "1"
      coverage_content_type: coordinate
  earth:
    dims: [earth]
    dtype: str
    attrs:
      long_name: Earth Reference Frame
      units: "1"
      coverage_content_type: coordinate

data_vars:
  vel:
    dims: [dir, range, time]
    dtype: float32
    attrs:
      long_name: Water Velocity
      standard_name: velocity_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water
      units: m/s
      valid_min: -8
      valid_max: 8
  vel_b5:
    dims: [dir, time_b5]
    dtype: float32
    attrs:
      long_name: Vertical Along-Beam Velocity
      standard_name: upward_sea_water_velocity
      units: m/s
      valid_min: -5
      valid_max: 5
  amp:
    dims: [beam, range, time]
    dtype: float32
    attrs:
      long_name: Acoustic Signal Amplitude
      standard_name: signal_intensity_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water
      units: dB
  corr:
    dims: [beam, range, time]
    dtype: int
    attrs:
      long_name: Acoustic Signal Correlation
      standard_name: beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water
      units: "%"
  depth:
    dims: [time]
    dtype: float32
    attrs:
      description:
        "Seafloor depth below water surface, calculated from temperature, salinity and
        pressure"
      long_name: Depth to Seafloor
      standard_name: depth
      units: m
      positive: down
  water_density:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Water Density
      standard_name: sea_water_density
      description: "Water density according to UNESCO 1981 equation of state"
      units: kg/m^3
  heading:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Heading
      standard_name: platform_orientation
      units: deg
      valid_min: -180
      valid_max: 180
  pitch:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pitch
      standard_name: platform_pitch
      units: deg
      valid_min: -180
      valid_max: 180
  roll:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Roll
      standard_name: platform_roll
      units: deg
      valid_min: -180
      valid_max: 180
  orientmat:
    dims: [earth, inst, time]
    dtype: float32
    attrs:
      description: Earth (ENU) to instrument (XYZ) orientation matrix
      long_name: Orientation Matrix
      units: "1"
  beam2inst_orientmat:
    dims: [beam, instrumentNortek]
    dtype: float
    attrs:
      description: "Beam to instrument orientation matrix"
      units: "1"
  speed_of_sound:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Speed of Sound
      standard_name: speed_of_sound_in_sea_water
      units: m/s
  pressure:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pressure
      standard_name: sea_water_pressure
      units: dbar
  temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Temperature
      standard_name: sea_water_temperature
      units: degC
  transmit_energy:
    dims: [time]
    dtype: int
    attrs:
      long_name: Transmit Energy
      standard_name: sound_pressure_level_of_acoustic_signal
      units: dB
  transmit_energy_b5:
    dims: [time_b5]
    dtype: int
    attrs:
      long_name: Beam 5 Transmit Energy
      standard_name: sound_pressure_level_of_acoustic_signal
      units: dB
  error:
    dims: [time]
    dtype: int
    attrs:
      long_name: Error Code
      units: "1"
  error_b5:
    dims: [time_b5]
    dtype: int
    attrs:
      long_name: Beam 5 Error Code
      units: "1"
  active_configuration:
    dims: [time]
    dtype: int
    attrs:
      description: "Active configuration for instruments running a dual profile"
      units: "1"
  boost_running_flag:
    dims: [time]
    dtype: int
    attrs:
      description: "Boost mode running (0 or 1)"
      units: "1"
  low_voltage_skip_flag:
    dims: [time]
    dtype: int
    attrs:
      description: "Ping skipped due to low voltage (0 or 1)"
      units: "1"
  telemetry_data_flag:
    dims: [time]
    dtype: int
    attrs:
      description: "Ping has associated telemetry data (0 or 1)"
      units: "1"
